name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "echo Skipping prisma generate in predev"
dev = "npx prisma migrate deploy && npm exec react-router dev"
