# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d502b734f2ad37cf0eb3b63420b5d516"
name = "Vinci Shoppable Videos"
application_url = "https://carrousel-pu4u.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes,write_app_proxy,read_orders"

[app_proxy]
url = "/proxy/carrousel"
prefix = "apps"
subpath = "carrousel"

[auth]
redirect_urls = [ "https://carrousel-pu4u.onrender.com/auth/callback" ]
